using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Avalonia.Controls;
using Avalonia.Headless;
using Avalonia.Headless.XUnit;
using Avalonia.VisualTree;
using DungeonApp.Desktop.Content;
using DungeonApp.Desktop.Shell.Sidebars;

namespace DungeonApp.Desktop.RenderingTests;

/// <summary>
/// Headless-rendering coverage for the bug the reading-only review missed: after 39a4bc5 the campaign
/// position and "Zmień system" rows reserve their row height but draw nothing (the author's own
/// screenshot is what this test was written from). Every other row on the sidebar is generated by an
/// <see cref="ItemsControl"/>; those two are a bare <c>ContentPresenter</c> outside any
/// <see cref="ItemsControl"/>, which is the one structural difference between the rows that draw and
/// the rows that do not.
/// <para>
/// <see cref="Every_row_draws_its_label_with_nonzero_bounds_after_a_system_is_chosen"/> is expected to
/// fail on the campaign-position and "Zmień system" rows until that structural difference is removed
/// (the brief's Zadanie 1) - it is written, and run, before that fix exists.
/// </para>
/// </summary>
public sealed class GlobalSidebarRenderingTests
{
    private const string CampaignTabIcon = "DungeonIconBookOpen";
    private const string SystemTabIcon = "DungeonIconDatabase";

    [AvaloniaFact]
    public void Every_row_draws_its_label_with_nonzero_bounds_after_a_system_is_chosen()
    {
        var window = BuildWindow(startCollapsed: false, out _);

        AssertRowDraws(window, "Kampanie");
        AssertRowDraws(window, "Biurko");
        AssertRowDraws(window, "Rejestr");
        AssertRowDraws(window, "Zmień system");
    }

    /// <summary>
    /// docs/architecture.md, "Zwijanie paska jak dawniej": in the collapsed rail, every row across all
    /// three categories is meant to form one continuous column with no gap wider than the spacing
    /// already used between two rows inside a single group - the pre-etap-1 behaviour with one heading.
    /// <para>
    /// Headless has no compositor-driven frame clock tied to wall time:
    /// <see cref="Avalonia.Headless.AvaloniaHeadlessPlatform.ForceRenderTimerTick"/>, tried first,
    /// advanced neither the heading Border's Height transition nor <see cref="Control.Bounds"/> even
    /// after many forced ticks. What headless *does* honour is that a transition only plays across a
    /// value change on a control that already rendered a prior frame - toggling
    /// <see cref="GlobalSidebarViewModel.IsCollapsed"/> before the view's first <c>Show()</c> gives it
    /// no earlier frame to transition from, so the collapsed state is simply what the first layout
    /// pass produces. That is the brief's "przy wyłączonych przejściach" case.
    /// </para>
    /// <para>
    /// Caveat worth recording: this asserts the *delivered* fix's geometry, not a regression guard
    /// against the pre-fix implementation. The pre-fix mechanism (a <c>TranslateTransform</c> on the
    /// item list) moves pixels only at render time and never changes <see cref="Control.Bounds"/> (an
    /// arrange-time value) at all, collapsed or not - so a Bounds-only assertion cannot fail against
    /// it either way. Swapping the fix for a Height animation (rather than a bigger translate) is what
    /// makes the gap observable here in the first place.
    /// </para>
    /// </summary>
    [AvaloniaFact]
    public void Collapsing_the_sidebar_leaves_no_gap_between_rows_of_different_groups()
    {
        var expandedWindow = BuildWindow(startCollapsed: false, out _);
        var rowsExpanded = GetNavButtons(expandedWindow);
        Assert.True(rowsExpanded.Count >= 4, $"Za mało wierszy do sprawdzenia przerw: {rowsExpanded.Count}.");
        var withinGroupGap = rowsExpanded[1].Bounds.Y - (rowsExpanded[0].Bounds.Y + rowsExpanded[0].Bounds.Height);

        var collapsedWindow = BuildWindow(startCollapsed: true, out _);
        var rowsCollapsed = GetNavButtons(collapsedWindow);
        Assert.True(rowsCollapsed.Count >= 4, $"Za mało wierszy do sprawdzenia przerw: {rowsCollapsed.Count}.");
        for (var i = 1; i < rowsCollapsed.Count; i++)
        {
            var gap = rowsCollapsed[i].Bounds.Y - (rowsCollapsed[i - 1].Bounds.Y + rowsCollapsed[i - 1].Bounds.Height);
            Assert.True(
                gap <= withinGroupGap + 0.5,
                $"Przerwa między wierszem {i - 1} a {i} po zwinięciu wynosi {gap}, " +
                $"oczekiwano nie więcej niż odstępu wewnątrz grupy ({withinGroupGap}).");
        }
    }

    private static Window BuildWindow(bool startCollapsed, out GlobalSidebarViewModel viewModel)
    {
        var systemTab = new SystemTabDeclaration("sys.registry", "Rejestr", SystemTabIcon, _ => new FakeTabContent());
        var campaignTab = new CampaignTabDeclaration(
            "camp.desk", "Biurko", CampaignTabIcon, _ => Task.FromResult<ITabContent>(new FakeTabContent()));

        viewModel = new GlobalSidebarViewModel(
            [systemTab],
            [campaignTab],
            () => Task.CompletedTask,
            _ => Task.CompletedTask,
            _ => { },
            () => Task.CompletedTask);

        if (startCollapsed)
        {
            viewModel.ToggleCollapsedCommand.Execute(null);
        }

        var view = new GlobalSidebarView { DataContext = viewModel };
        var window = new Window { Content = view, Width = 224, Height = 728 };
        window.Show();
        window.GetLayoutManager()!.ExecuteLayoutPass();

        return window;
    }

    /// <summary>Every "Button.nav-button" in document order - the four rows this sidebar renders today.</summary>
    private static IReadOnlyList<Button> GetNavButtons(Window window) =>
        [.. window.GetVisualDescendants().OfType<Button>().Where(b => b.Classes.Contains("nav-button"))];

    private static void AssertRowDraws(Window window, string label)
    {
        var textBlock = window.GetVisualDescendants()
            .OfType<TextBlock>()
            .FirstOrDefault(tb => tb.Text == label);

        Assert.True(textBlock is not null, $"Brak TextBlock z etykietą '{label}' w drzewie wizualnym.");
        Assert.True(
            textBlock!.Bounds.Width > 0 && textBlock.Bounds.Height > 0,
            $"TextBlock '{label}' ma zerowe wymiary: {textBlock.Bounds}.");
    }
}
