using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Headless;
using Avalonia.Headless.XUnit;
using Avalonia.VisualTree;
using DungeonApp.Desktop.Content;
using DungeonApp.Desktop.Shell.Sidebars;

namespace DungeonApp.Desktop.RenderingTests;

/// <summary>
/// Headless-rendering coverage for the bug the reading-only review missed: after 39a4bc5 the campaign
/// position and "Zmień system" rows reserve their row height but draw nothing (the author's own
/// screenshot is what this test was written from). Every other row on the sidebar is generated by an
/// <see cref="ItemsControl"/>; those two are a bare <c>ContentPresenter</c> outside any
/// <see cref="ItemsControl"/>, which is the one structural difference between the rows that draw and
/// the rows that do not.
/// <para>
/// <see cref="Every_row_draws_its_label_with_nonzero_bounds_after_a_system_is_chosen"/> is expected to
/// fail on the campaign-position and "Zmień system" rows until that structural difference is removed
/// (the brief's Zadanie 1) - it is written, and run, before that fix exists.
/// </para>
/// </summary>
public sealed class GlobalSidebarRenderingTests
{
    private const string CampaignTabIcon = "DungeonIconBookOpen";
    private const string SystemTabIcon = "DungeonIconDatabase";

    [AvaloniaFact]
    public void Every_row_draws_its_label_with_nonzero_bounds_after_a_system_is_chosen()
    {
        var window = BuildWindow(startCollapsed: false, out _);

        AssertRowDraws(window, "Kampanie");
        AssertRowDraws(window, "Biurko");
        AssertRowDraws(window, "Rejestr");
        AssertRowDraws(window, "Ustawienia");
    }

    /// <summary>
    /// docs/architecture.md, "Zwijanie paska jak dawniej" no longer asks for one continuous column -
    /// the author reversed that call (etap 4, brief A.6): collapsing must leave a deliberate, designed
    /// gap between the Kampania group and the Biblioteka group (still named System in code -
    /// <see cref="GlobalSidebarViewModel.SystemTabItems"/> - but labelled "BIBLIOTEKA" on screen), not
    /// the small within-group spacing every other adjacent pair of rows gets.
    /// <para>
    /// The expected gap is exactly the two view-local values that compose it in
    /// GlobalSidebarView.axaml: <c>DungeonSpacingLg</c> (16, the outer StackPanel's own
    /// <c>Spacing</c> between the two groups) plus the Biblioteka group's own items-list top margin
    /// (8, unchanged from before this change). Asserting the precise sum, not merely "bigger than
    /// zero", is what tells a designed gap apart from an accidental one.
    /// </para>
    /// <para>
    /// Headless has no compositor-driven frame clock tied to wall time:
    /// <see cref="Avalonia.Headless.AvaloniaHeadlessPlatform.ForceRenderTimerTick"/>, tried first,
    /// advanced neither the heading Border's Height transition nor <see cref="Control.Bounds"/> even
    /// after many forced ticks. What headless *does* honour is that a transition only plays across a
    /// value change on a control that already rendered a prior frame - toggling
    /// <see cref="GlobalSidebarViewModel.IsCollapsed"/> before the view's first <c>Show()</c> gives it
    /// no earlier frame to transition from, so the collapsed state is simply what the first layout
    /// pass produces.
    /// </para>
    /// </summary>
    [AvaloniaFact]
    public void Collapsing_the_sidebar_leaves_a_designed_gap_between_kampania_and_biblioteka()
    {
        const double designedGroupGap = 16 + 8; // DungeonSpacingLg + Biblioteka's own items-list top margin.

        var collapsedWindow = BuildWindow(startCollapsed: true, out _);
        var rows = GetNavButtons(collapsedWindow);
        Assert.True(rows.Count >= 4, $"Za mało wierszy do sprawdzenia przerw: {rows.Count}.");

        // rows[0]/[1] are both Kampania (campaign position, then its one campaign tab); rows[2] is
        // Biblioteka's own single tab - the boundary this test is actually about.
        var withinGroupGap = TopOf(rows[1], collapsedWindow) - Bottom(rows[0], collapsedWindow);
        var groupBoundaryGap = TopOf(rows[2], collapsedWindow) - Bottom(rows[1], collapsedWindow);

        Assert.True(withinGroupGap is > 0 and < designedGroupGap, $"Odstęp wewnątrz grupy Kampania ({withinGroupGap}) powinien być mniejszy niż odstęp między grupami.");
        Assert.Equal(designedGroupGap, groupBoundaryGap, precision: 1);
    }

    /// <summary>
    /// docs/tasks.md, etap 4, brief A.5: the Aplikacja category (on screen, "SYSTEM" - today just
    /// "Ustawienia") is pinned to the sidebar's own bottom edge in both collapse states, and
    /// collapsing only ever hides its own heading - its row must never move vertically. Both halves
    /// are asserted: the row's Y is identical whether the sidebar is collapsed or not, and that Y
    /// sits exactly this group's own trailing margin (8, GlobalSidebarView.axaml) above the sidebar's
    /// own rendered bottom edge in either state.
    /// </summary>
    [AvaloniaFact]
    public void The_aplikacja_categorys_row_stays_at_the_sidebars_bottom_edge_in_both_collapse_states()
    {
        const double trailingMargin = 8;

        var expandedWindow = BuildWindow(startCollapsed: false, out _);
        var expandedSettingsRow = FindRowByLabel(expandedWindow, "Ustawienia");

        var collapsedWindow = BuildWindow(startCollapsed: true, out _);
        var collapsedSettingsRow = FindRowByLabel(collapsedWindow, "Ustawienia");

        Assert.Equal(TopOf(expandedSettingsRow, expandedWindow), TopOf(collapsedSettingsRow, collapsedWindow), precision: 1);

        AssertSitsAboveTheBottomEdgeBy(expandedWindow, expandedSettingsRow, trailingMargin);
        AssertSitsAboveTheBottomEdgeBy(collapsedWindow, collapsedSettingsRow, trailingMargin);
    }

    private static void AssertSitsAboveTheBottomEdgeBy(Window window, Button row, double expectedMargin)
    {
        var marginBelowRow = window.Bounds.Height - Bottom(row, window);

        Assert.Equal(expectedMargin, marginBelowRow, precision: 1);
    }

    private static Button FindRowByLabel(Window window, string label) =>
        GetNavButtons(window).Single(button =>
            button.GetVisualDescendants().OfType<TextBlock>().Any(tb => tb.Text == label));

    /// <summary>
    /// A generated row's own <see cref="Control.Bounds"/> is relative to its immediate visual parent -
    /// for an <see cref="ItemsControl"/>'s generated item that is the per-item container Avalonia
    /// wraps it in, not the sidebar - so every row reports the same Bounds.Y (0) regardless of where
    /// it actually draws. <see cref="Visual.TranslatePoint(Point, Visual)"/> against the window itself
    /// is what turns that into a comparable, window-relative coordinate.
    /// </summary>
    private static double TopOf(Visual visual, Visual window) =>
        visual.TranslatePoint(new Point(0, 0), window)!.Value.Y;

    private static double Bottom(Control control, Visual window) =>
        TopOf(control, window) + control.Bounds.Height;

    /// <summary>
    /// docs/tasks.md, zadanie 2: the sidebar shown after choosing a system must have its target
    /// collapse state from the very first frame, never expanded-then-collapsing. Both
    /// <see cref="Sidebar_constructed_already_collapsed_has_collapsed_heading_height_on_the_first_frame"/>
    /// and its expanded counterpart build the view model with <c>startCollapsed</c> passed to the
    /// constructor - the fix - rather than toggling after construction the way <see cref="BuildWindow"/>
    /// above still does for the pre-existing row-gap coverage.
    /// </summary>
    [AvaloniaFact]
    public void Sidebar_constructed_already_collapsed_has_collapsed_heading_height_on_the_first_frame()
    {
        var window = BuildWindowConstructedAt(startCollapsed: true);

        AssertEveryHeadingHeight(window, expected: 0);
    }

    [AvaloniaFact]
    public void Sidebar_constructed_already_expanded_has_expanded_heading_height_on_the_first_frame()
    {
        var window = BuildWindowConstructedAt(startCollapsed: false);

        AssertEveryHeadingHeight(window, expected: 44);
    }

    /// <summary>
    /// docs/tasks.md, zadanie 2, the "Zmień system" case: AppShellView.axaml hosts the sidebar through
    /// a <c>ContentControl</c> bound to <c>AppShellViewModel.Sidebar</c>, resolved by a
    /// <see cref="GlobalSidebarViewModel"/> <c>DataTemplate</c> - never a persistent
    /// <see cref="GlobalSidebarView"/> instance whose <c>DataContext</c> is merely rebound. That
    /// matters because a first, manual check (rebinding <c>DataContext</c> on one already-shown
    /// <see cref="GlobalSidebarView"/>) still showed an expanded frame after the swap: the control had
    /// already rendered once, so its Width/heading transitions played across the change instead of
    /// skipping it. A <c>DataTemplate</c> behind a <c>ContentControl</c> instantiates a fresh visual
    /// per distinct <c>Content</c> reference, which is what this test exercises and what
    /// AppShellView.axaml now relies on.
    /// </summary>
    [AvaloniaFact]
    public void A_fresh_sidebar_built_by_the_content_templates_data_template_shows_the_next_systems_collapse_state_immediately()
    {
        var host = new ContentControl();
        host.DataTemplates.Add(new Avalonia.Controls.Templates.FuncDataTemplate<GlobalSidebarViewModel>(
            (vm, _) => new GlobalSidebarView { DataContext = vm, Width = vm.SidebarWidth }));

        var window = new Window { Content = host, Width = 224, Height = 728 };
        window.Show();

        host.Content = BuildSidebarViewModel(startCollapsed: false);
        window.GetLayoutManager()!.ExecuteLayoutPass();
        AssertEveryHeadingHeight(window, expected: 44);

        // The "Zmień system" moment: a second, distinct GlobalSidebarViewModel with the collapse
        // state the frame remembered from the first system's sidebar (docs/tasks.md, zadanie 3).
        host.Content = BuildSidebarViewModel(startCollapsed: true);
        window.GetLayoutManager()!.ExecuteLayoutPass();

        AssertEveryHeadingHeight(window, expected: 0);
    }

    private static GlobalSidebarViewModel BuildSidebarViewModel(bool startCollapsed)
    {
        var systemTab = new SystemTabDeclaration("sys.registry", "Rejestr", SystemTabIcon, () => new FakeTabContent());
        var campaignTab = new CampaignTabDeclaration(
            "camp.desk", "Biurko", CampaignTabIcon, _ => Task.FromResult<ITabContent>(new FakeTabContent()));

        return new GlobalSidebarViewModel(
            [systemTab],
            [campaignTab],
            () => Task.CompletedTask,
            _ => Task.CompletedTask,
            _ => { },
            () => Task.CompletedTask,
            startCollapsed);
    }

    private static Window BuildWindow(bool startCollapsed, out GlobalSidebarViewModel viewModel)
    {
        var systemTab = new SystemTabDeclaration("sys.registry", "Rejestr", SystemTabIcon, () => new FakeTabContent());
        var campaignTab = new CampaignTabDeclaration(
            "camp.desk", "Biurko", CampaignTabIcon, _ => Task.FromResult<ITabContent>(new FakeTabContent()));

        viewModel = new GlobalSidebarViewModel(
            [systemTab],
            [campaignTab],
            () => Task.CompletedTask,
            _ => Task.CompletedTask,
            _ => { },
            () => Task.CompletedTask);

        if (startCollapsed)
        {
            viewModel.ToggleCollapsedCommand.Execute(null);
        }

        var view = new GlobalSidebarView { DataContext = viewModel };
        var window = new Window { Content = view, Width = 224, Height = 728 };
        window.Show();
        window.GetLayoutManager()!.ExecuteLayoutPass();

        return window;
    }

    /// <summary>Builds the sidebar with its collapse state fixed by the constructor's own <c>startCollapsed</c> parameter - never by a post-construction toggle.</summary>
    private static Window BuildWindowConstructedAt(bool startCollapsed)
    {
        var systemTab = new SystemTabDeclaration("sys.registry", "Rejestr", SystemTabIcon, () => new FakeTabContent());
        var campaignTab = new CampaignTabDeclaration(
            "camp.desk", "Biurko", CampaignTabIcon, _ => Task.FromResult<ITabContent>(new FakeTabContent()));

        var viewModel = new GlobalSidebarViewModel(
            [systemTab],
            [campaignTab],
            () => Task.CompletedTask,
            _ => Task.CompletedTask,
            _ => { },
            () => Task.CompletedTask,
            startCollapsed);

        var view = new GlobalSidebarView { DataContext = viewModel };
        var window = new Window { Content = view, Width = 224, Height = 728 };
        window.Show();
        window.GetLayoutManager()!.ExecuteLayoutPass();

        return window;
    }

    /// <summary>Each of the three group headings' own Border.Height (KAMPANIA/SYSTEM/APLIKACJA) - bound to <see cref="GlobalSidebarViewModel.HeadingHeight"/>.</summary>
    private static void AssertEveryHeadingHeight(Window window, double expected)
    {
        var headings = window.GetVisualDescendants()
            .OfType<Border>()
            .Where(border => border.Child is TextBlock textBlock && textBlock.Classes.Contains("sidebar-section-heading"))
            .ToList();

        Assert.True(headings.Count == 3, $"Oczekiwano trzech nagłówków grup, znaleziono {headings.Count}.");
        Assert.All(headings, border => Assert.Equal(expected, border.Bounds.Height));
    }

    /// <summary>Every "Button.nav-button" in document order - the four rows this sidebar renders today.</summary>
    private static IReadOnlyList<Button> GetNavButtons(Window window) =>
        [.. window.GetVisualDescendants().OfType<Button>().Where(b => b.Classes.Contains("nav-button"))];

    private static void AssertRowDraws(Window window, string label)
    {
        var textBlock = window.GetVisualDescendants()
            .OfType<TextBlock>()
            .FirstOrDefault(tb => tb.Text == label);

        Assert.True(textBlock is not null, $"Brak TextBlock z etykietą '{label}' w drzewie wizualnym.");
        Assert.True(
            textBlock!.Bounds.Width > 0 && textBlock.Bounds.Height > 0,
            $"TextBlock '{label}' ma zerowe wymiary: {textBlock.Bounds}.");
    }
}
