using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Avalonia.Controls;
using Avalonia.Headless;
using Avalonia.Headless.XUnit;
using Avalonia.VisualTree;
using DungeonApp.Desktop.Content;
using DungeonApp.Desktop.Shell.Sidebars;

namespace DungeonApp.Desktop.RenderingTests;

/// <summary>
/// Headless-rendering coverage for the bug the reading-only review missed: after 39a4bc5 the campaign
/// position and "Zmień system" rows reserve their row height but draw nothing (the author's own
/// screenshot is what this test was written from). Every other row on the sidebar is generated by an
/// <see cref="ItemsControl"/>; those two are a bare <c>ContentPresenter</c> outside any
/// <see cref="ItemsControl"/>, which is the one structural difference between the rows that draw and
/// the rows that do not.
/// <para>
/// <see cref="Every_row_draws_its_label_with_nonzero_bounds_after_a_system_is_chosen"/> is expected to
/// fail on the campaign-position and "Zmień system" rows until that structural difference is removed
/// (the brief's Zadanie 1) - it is written, and run, before that fix exists.
/// </para>
/// </summary>
public sealed class GlobalSidebarRenderingTests
{
    private const string CampaignTabIcon = "DungeonIconBookOpen";
    private const string SystemTabIcon = "DungeonIconDatabase";

    [AvaloniaFact]
    public void Every_row_draws_its_label_with_nonzero_bounds_after_a_system_is_chosen()
    {
        var window = BuildWindow(out _);

        AssertRowDraws(window, "Kampanie");
        AssertRowDraws(window, "Biurko");
        AssertRowDraws(window, "Rejestr");
        AssertRowDraws(window, "Zmień system");
    }

    /// <summary>
    /// docs/architecture.md, "Zwijanie paska jak dawniej": in the collapsed rail, every row across all
    /// three categories is meant to form one continuous column with no gap wider than the spacing
    /// already used between two rows inside a single group - the pre-etap-1 behaviour with one heading.
    /// Headless has no compositor-driven frame clock tied to wall time, so the transition is forced to
    /// completion with <see cref="AvaloniaHeadlessPlatform.ForceRenderTimerTick"/> rather than awaited.
    /// </summary>
    [AvaloniaFact]
    public void Collapsing_the_sidebar_leaves_no_gap_between_rows_of_different_groups()
    {
        var window = BuildWindow(out var viewModel);
        var rowsBefore = GetNavButtons(window);
        Assert.True(rowsBefore.Count >= 4, $"Za mało wierszy do sprawdzenia przerw: {rowsBefore.Count}.");
        var withinGroupGap = rowsBefore[1].Bounds.Y - (rowsBefore[0].Bounds.Y + rowsBefore[0].Bounds.Height);

        viewModel.ToggleCollapsedCommand.Execute(null);
        AvaloniaHeadlessPlatform.ForceRenderTimerTick(20);
        window.GetLayoutManager()!.ExecuteLayoutPass();

        var rowsAfter = GetNavButtons(window);
        for (var i = 1; i < rowsAfter.Count; i++)
        {
            var gap = rowsAfter[i].Bounds.Y - (rowsAfter[i - 1].Bounds.Y + rowsAfter[i - 1].Bounds.Height);
            Assert.True(
                gap <= withinGroupGap + 0.5,
                $"Przerwa między wierszem {i - 1} a {i} po zwinięciu wynosi {gap}, " +
                $"oczekiwano nie więcej niż odstępu wewnątrz grupy ({withinGroupGap}).");
        }
    }

    private static Window BuildWindow(out GlobalSidebarViewModel viewModel)
    {
        var systemTab = new SystemTabDeclaration("sys.registry", "Rejestr", SystemTabIcon, _ => new FakeTabContent());
        var campaignTab = new CampaignTabDeclaration(
            "camp.desk", "Biurko", CampaignTabIcon, _ => Task.FromResult<ITabContent>(new FakeTabContent()));

        viewModel = new GlobalSidebarViewModel(
            [systemTab],
            [campaignTab],
            () => Task.CompletedTask,
            _ => Task.CompletedTask,
            _ => { },
            () => Task.CompletedTask);

        var view = new GlobalSidebarView { DataContext = viewModel };
        var window = new Window { Content = view, Width = 224, Height = 728 };
        window.Show();
        window.GetLayoutManager()!.ExecuteLayoutPass();

        return window;
    }

    /// <summary>Every "Button.nav-button" in document order - the four rows this sidebar renders today.</summary>
    private static IReadOnlyList<Button> GetNavButtons(Window window) =>
        [.. window.GetVisualDescendants().OfType<Button>().Where(b => b.Classes.Contains("nav-button"))];

    private static void AssertRowDraws(Window window, string label)
    {
        var textBlock = window.GetVisualDescendants()
            .OfType<TextBlock>()
            .FirstOrDefault(tb => tb.Text == label);

        Assert.True(textBlock is not null, $"Brak TextBlock z etykietą '{label}' w drzewie wizualnym.");
        Assert.True(
            textBlock!.Bounds.Width > 0 && textBlock.Bounds.Height > 0,
            $"TextBlock '{label}' ma zerowe wymiary: {textBlock.Bounds}.");
    }
}
